/*

 TILEBKRMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\devsl\Desktop\attempt1\wfctiles1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tilebkrmap_h_INCLUDE
#define __tilebkrmap_h_INCLUDE

#define tilebkrmaplabelWidth 20
#define tilebkrmaplabelHeight 18
#define tilebkrmaplabelBank 0

extern const unsigned char tilebkrmaplabel[];

#endif

/* End of TILEBKRMAP.H */
